# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "styre79/skbot"
  tag: "v1.0.3-c7b2b46"
  os: linux
  arch: amd64
secret:
  name: "skbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
